### ISSUE TITLE
High Score System

### ISSUE THREAD

**Issue by pobryan** [pobryan/groupproject-team-4-namco-Galaga#3]
I think the game would benefit by having a better high-score system, the one it has right now is inconsistent and does not keep data from each time it is started. A great addition would be to have the highest score saved so it serves a purpose. The easiest way to do this is would be to create a file/file system to save/access data whenever needed, pulling data in and out. The scores, menu, and graphics classes would likely need to be changed.

**Comment by onzfonz** [comment]
Yes, go ahead and do this one , and have it so that the scores persist even after closing the game
